### ISSUE TITLE
Heroku Deploy fails to compile app: AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by JAertgeerts** [benedwards44/sforgcompare#3]
```
     $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "manage.py", line 10, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
           commands = get_commands()
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands
           apps = settings.INSTALLED_APPS
         File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
           self._setup(name)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
           self._wrapped = Settings(settings_module)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
           mod = importlib.import_module(self.SETTINGS_MODULE)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
           __import__(name)
         File "/app/sforgcompare/settings.py", line 92, in <module>
           redis_url = urlparse.urlparse(os.environ.get('REDIS_URL'))
         File "/app/.heroku/python/lib/python2.7/urlparse.py", line 143, in urlparse
           tuple = urlsplit(url, scheme, allow_fragments)
         File "/app/.heroku/python/lib/python2.7/urlparse.py", line 182, in urlsplit
           i = url.find(':')
       AttributeError: 'NoneType' object has no attribute 'find'
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app
```

**Comment by JAertgeerts** [comment]
RedisToGo sets env variable as REDISTOGO_URL instead of REDIS_URL. Changing REDISTOGO to Heroku REDIS that does serve this env. var and offers a better free plan.

**Comment by JAertgeerts** [comment]
Still some other configuration required to make it generic so we can deploy in Heroku without changes. Making them now & creating PR
